- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: 0644
- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    update_cache: false
- name: Download Hashicorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc
    mode: 0644
- name: Add Hashicorp repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
    update_cache: false
- name: Install Packages
  ansible.builtin.apt:
    name:
      - qemu-kvm
      - btop
      - libvirt-daemon-system
      - docker-ce
      - ksmtuned
      - zsh
      - libvirt-clients
      - libxslt-dev
      - libxml2-dev
      - libvirt-dev
      - zlib1g-dev
      - ruby-dev
      - ruby-libvirt
      - ebtables
      - keyboard-configuration
      - console-setup
      - net-tools
      - vagrant
      - fzf
      - pipx
      - pipenv
      - ripgrep
    update_cache: true
  tags: packages
- name: Change local to FR
  community.general.locale_gen:
    name: fr_FR.UTF-8
    state: present
  tags: local
- name: install Azure cli
  ansible.builtin.shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash
- name: dpkg-reconfigure
  shell: |
    dpkg-reconfigure -f noninteractive keyboard-configuration && \
    localectl set-locale LANG=fr_FR.UTF8 LANGUAGE=fr_FR.UTF8 && \
    timedatectl set-timezone Europe/Paris && \
    update-locale LANG=fr_FR.UTF-8
